import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettier from "eslint-config-prettier/flat";
import { architecture } from "./eslint/architecture.mjs";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Components generated by the shadcn/ui and AI Elements CLIs stay as
  // generated, so they can be updated from the registries. The React
  // Compiler skips the few components these rules flag.
  {
    files: ["src/components/ui/**", "src/components/ai-elements/**"],
    rules: {
      "react-hooks/set-state-in-effect": "off",
      "react-hooks/static-components": "off",
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { ignoreRestSiblings: true },
      ],
    },
  },
  // Folder structure and layer boundaries (docs/ARCHITECTURE.md).
  ...architecture,
  // Disable stylistic rules that conflict with Prettier; must come last.
  prettier,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "coverage/**",
    "playwright-report/**",
    "test-results/**",
    // Git worktrees that Claude Code agents work in.
    ".claude/worktrees/**",
    // Generated by Vercel Workflow:
    "src/app/.well-known/workflow/**",
    ".swc/**",
  ]),
]);

export default eslintConfig;
