import { messageText } from "@/features/chat/domain/message-text";
import type { ChatUIMessage } from "@/features/chat/types";

/** The longest label shown for an untitled Chat, before the ellipsis. */
const MAX_LABEL_LENGTH = 40;

/** The longest generated title, before the ellipsis. */
const MAX_GENERATED_TITLE_LENGTH = 60;

/** `text` on one line, cut at a word to at most `max` characters plus "…". */
function shortenAtWord(text: string, max: number): string {
  const line = text.replace(/\s+/g, " ").trim();
  if (line.length <= max) return line;

  const head = line.slice(0, max + 1);
  const wordEnd = head.lastIndexOf(" ");
  return `${head.slice(0, wordEnd > 0 ? wordEnd : max).replace(/[\s,;:.-]+$/, "")}…`;
}

/**
 * What a message is about, in words: its text, or for a message of only
 * attached Materials, the first Material's name.
 */
export function messageGist(parts: ChatUIMessage["parts"]): string {
  const text = messageText(parts);
  if (text.trim() !== "") return text;
  const material = parts.find((part) => part.type === "data-material");
  return material?.data.name ?? "";
}

/**
 * How a Chat is named in the Chat list: its title, or until it has one, its
 * first message on one line, shortened at a word (`messageGist`).
 */
export function chatLabel({
  title,
  firstMessage,
}: {
  title: string | null;
  /** The parts of the Chat's first message. */
  firstMessage: ChatUIMessage["parts"] | null;
}): string {
  if (title?.trim()) return title.trim();

  const text = shortenAtWord(
    firstMessage ? messageGist(firstMessage) : "",
    MAX_LABEL_LENGTH,
  );
  return text === "" ? "New chat" : text;
}

/**
 * A title generated by the AI as the Chat's title: its first line without
 * quotes or Markdown, shortened at a word. Null when nothing is left.
 */
export function generatedTitle(text: string): string | null {
  const firstLine = text
    .split("\n")
    .map((line) => line.replace(/^[\s#*_"'“”‘’`]+|[\s*_"'“”‘’`.]+$/g, ""))
    .find((line) => line !== "");
  return firstLine
    ? shortenAtWord(firstLine, MAX_GENERATED_TITLE_LENGTH)
    : null;
}
