/** The longest label shown for an untitled Chat, before the ellipsis. */
const MAX_LABEL_LENGTH = 40;

/** The longest generated title, before the ellipsis. */
const MAX_GENERATED_TITLE_LENGTH = 60;

/** `text` on one line, cut at a word to at most `max` characters plus "…". */
function shortenAtWord(text: string, max: number): string {
  const line = text.replace(/\s+/g, " ").trim();
  if (line.length <= max) return line;

  const head = line.slice(0, max + 1);
  const wordEnd = head.lastIndexOf(" ");
  return `${head.slice(0, wordEnd > 0 ? wordEnd : max).replace(/[\s,;:.-]+$/, "")}…`;
}

/**
 * How a Chat is named in the Chat list: its title, or until it has one, its
 * first message on one line, shortened at a word.
 */
export function chatLabel({
  title,
  firstMessage,
}: {
  title: string | null;
  firstMessage: string | null;
}): string {
  if (title?.trim()) return title.trim();

  const text = shortenAtWord(firstMessage ?? "", MAX_LABEL_LENGTH);
  return text === "" ? "New chat" : text;
}

/**
 * A title generated by the AI as the Chat's title: its first line without
 * quotes or Markdown, shortened at a word. Null when nothing is left.
 */
export function generatedTitle(text: string): string | null {
  const firstLine = text
    .split("\n")
    .map((line) => line.replace(/^[\s#*_"'“”‘’`]+|[\s*_"'“”‘’`.]+$/g, ""))
    .find((line) => line !== "");
  return firstLine
    ? shortenAtWord(firstLine, MAX_GENERATED_TITLE_LENGTH)
    : null;
}
