-- Materials: files a Student uploads to one of their Courses (#37).
-- The bytes live in the `course-files` bucket at
-- `<owner id>/<course id>/<material id>`; this table registers them.

create table public.materials (
  -- Generated by the browser before uploading, so the object's path is known
  -- up front.
  id uuid primary key default gen_random_uuid(),
  owner uuid not null default auth.uid() references public.profiles (id) on delete cascade,
  course_id uuid not null references public.courses (id) on delete cascade,
  -- Trimmed by the app; the check refuses blank, padded or overlong names.
  name text not null check (name = btrim(name) and char_length(name) between 1 and 200),
  media_type text not null check (
    media_type in ('application/pdf', 'image/png', 'image/jpeg', 'image/webp')
  ),
  -- At most 20 MB, below the bucket's 50 MB limit.
  size_bytes bigint not null check (size_bytes between 1 and 20971520),
  storage_path text not null check (
    storage_path = owner::text || '/' || course_id::text || '/' || id::text
  ),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.materials is 'A file a Student uploaded to one Course. The bytes are in the course-files bucket at storage_path.';

create index materials_course_id_created_at_idx on public.materials (course_id, created_at desc);
create index materials_owner_idx on public.materials (owner);

create trigger materials_set_updated_at
before update on public.materials
for each row execute function private.set_updated_at();

-- Row Level Security: a Student reads and changes only their own Materials,
-- and adds them only to their own Courses.
alter table public.materials enable row level security;

create policy "Students can read their own materials"
on public.materials
for select
to authenticated
using ((select auth.uid()) = owner);

create policy "Students can add materials to their own courses"
on public.materials
for insert
to authenticated
with check (
  (select auth.uid()) = owner
  and exists (
    select 1 from public.courses
    where courses.id = course_id and courses.owner = (select auth.uid())
  )
);

create policy "Students can update their own materials"
on public.materials
for update
to authenticated
using ((select auth.uid()) = owner)
with check ((select auth.uid()) = owner);

create policy "Students can delete their own materials"
on public.materials
for delete
to authenticated
using ((select auth.uid()) = owner);

-- Grant only what the policies allow. Only the name changes.
revoke all on table public.materials from anon, authenticated;
grant select, insert, delete on table public.materials to authenticated;
grant update (name) on table public.materials to authenticated;
